import type {
  AccountNode,
  CommunityNode,
  Edge,
  InvestigationGraph,
} from "./types";

const accounts: AccountNode[] = [
  {
    id: "A1",
    kind: "account",
    username: "Gold_Paint_3490",
    pattern: "Word_Word_NNNN",
    created: "2025-05-20",
    karma: 1482,
    linkKarma: 1423,
    commentKarma: 59,
    isMod: false,
    language: "English",
    peakUtc: "20:00-23:00",
    removalRatePct: 22,
    cluster: "CL1b_activity_compression",
    notes: "11mo old account, 82 events crammed into 2 days (Apr 13-15).",
  },
  {
    id: "A2",
    kind: "account",
    username: "Material_Baby_7878",
    pattern: "Word_Word_NNNN",
    created: "2025-11-09",
    karma: 2917,
    linkKarma: 2910,
    commentKarma: 7,
    isMod: false,
    language: "Spanish",
    peakUtc: "19:00-22:00",
    removalRatePct: 31,
    cluster: "CL4_normal_users",
    notes: "31% removal rate, 99.8% link karma, default profile.",
  },
  {
    id: "A3",
    kind: "account",
    username: "KangarooEuphoric2265",
    pattern: "WordWordNNNN",
    created: "2024-04-17",
    karma: 68426,
    linkKarma: 57926,
    commentKarma: 10500,
    isMod: false,
    language: "English",
    peakUtc: "18:00-21:00",
    removalRatePct: null,
    cluster: "CL1_hidden_profiles",
    notes: "Hidden profile (privacy setting). 13 visible events / 350 days.",
  },
  {
    id: "A4",
    kind: "account",
    username: "Least_Egg_9371",
    pattern: "Word_Word_NNNN",
    created: "2025-05-13",
    karma: 42042,
    linkKarma: 15664,
    commentKarma: 26378,
    isMod: true,
    language: "English",
    peakUtc: "15:00-18:00",
    removalRatePct: null,
    cluster: "CL1_hidden_profiles",
    notes: "Hidden profile. Created 7 days before A1. Title: Hyposelenia.",
  },
  {
    id: "A5",
    kind: "account",
    username: "Emotional_Hyena5867",
    pattern: "Word_Word_NNNN",
    created: "2026-01-29",
    karma: 418,
    linkKarma: 14,
    commentKarma: 404,
    isMod: false,
    language: "English",
    peakUtc: "13:00-16:00",
    removalRatePct: 0,
    cluster: "CL4_normal_users",
    notes: "Indian anime fan. Peak matches IST evening. No flags.",
  },
  {
    id: "A6",
    kind: "account",
    username: "Sensitive-Hotel-9871",
    pattern: "Word-Word-NNNN",
    created: "2022-07-08",
    karma: 468066,
    linkKarma: 89867,
    commentKarma: 378199,
    isMod: true,
    language: "English",
    peakUtc: "15:00-18:00",
    removalRatePct: 9,
    cluster: "CL4_normal_users",
    notes: "US-based poweruser. 46+ subreddits. Long analytical comments.",
  },
  {
    id: "A7",
    kind: "account",
    username: "Local-Combination-46",
    pattern: "Word-Word-NN",
    created: "2021-11-16",
    karma: 1797,
    linkKarma: 1471,
    commentKarma: 326,
    isMod: false,
    language: "English",
    peakUtc: "06:00-09:00",
    removalRatePct: 2,
    cluster: "CL2_late_night_pair",
    notes: "Heaviest EVA concentration (47%). Same-minute activity with A8.",
  },
  {
    id: "A8",
    kind: "account",
    username: "Vast-Walk-5938",
    pattern: "Word-Word-NNNN",
    created: "2024-03-11",
    karma: 1086,
    linkKarma: 1,
    commentKarma: 1085,
    isMod: false,
    language: "English",
    peakUtc: "04:00-07:00",
    removalRatePct: 0,
    cluster: "CL2_late_night_pair",
    notes: "99.9% comment karma. Trolls corporate ads. Same-minute with A7.",
  },
];

const communities: CommunityNode[] = [
  {
    id: "C1",
    kind: "community",
    name: "r/NeonGenesisEvangelion",
    subscribers: 112850,
    notes: "All 8 accounts active here. Investigation epicenter.",
  },
  {
    id: "C2",
    kind: "community",
    name: "r/evangelion",
    subscribers: 1118573,
    notes: "A3, A6, A7, A8 also active here.",
  },
  {
    id: "C3",
    kind: "community",
    name: "r/Darkraiposting",
    subscribers: 9126,
    notes: "A2's primary community. Spanish-language fan sub.",
  },
  {
    id: "C4",
    kind: "community",
    name: "r/AskReddit",
    subscribers: null,
    notes: "A1's primary community.",
  },
  {
    id: "C5",
    kind: "community",
    name: "r/OriginalCharacterDB",
    subscribers: 7005,
    notes: "A7's secondary community. OC battle sub.",
  },
  {
    id: "C6",
    kind: "community",
    name: "r/AskOuija",
    subscribers: null,
    notes: "A8's primary community. Letter-by-letter word game.",
  },
];

const edges: Edge[] = [
  // Account -> Community membership / activity
  {
    from: "A1",
    to: "C1",
    kind: "posts_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "screenshots 1, 3; extended data (3 posts)",
  },
  {
    from: "A1",
    to: "C4",
    kind: "posts_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "30 posts in primary community",
  },
  {
    from: "A2",
    to: "C1",
    kind: "posts_in",
    deltaMinutes: null,
    timestamp: "2026-03",
    notes: "screenshot 2; 4 posts, 1 removed",
  },
  {
    from: "A2",
    to: "C3",
    kind: "posts_in",
    deltaMinutes: null,
    timestamp: "2026-03",
    notes: "58 posts (77% of activity)",
  },
  {
    from: "A3",
    to: "C1",
    kind: "posts_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "screenshot 4; via subreddit listing (submitted.json empty)",
  },
  {
    from: "A3",
    to: "C2",
    kind: "posts_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "Primary visible interest",
  },
  {
    from: "A4",
    to: "C1",
    kind: "posts_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "screenshot 5; 3 posts (209+ upvotes)",
  },
  {
    from: "A5",
    to: "C1",
    kind: "comments_in",
    deltaMinutes: null,
    timestamp: "2026-04-05",
    notes: "Comment on A3's post",
  },
  {
    from: "A6",
    to: "C1",
    kind: "comments_in",
    deltaMinutes: null,
    timestamp: "2026-04-14T17:54Z",
    notes: "Comment on A4's post (screenshot 5)",
  },
  {
    from: "A6",
    to: "C2",
    kind: "comments_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "Active in EVA community",
  },
  {
    from: "A7",
    to: "C1",
    kind: "comments_in",
    deltaMinutes: null,
    timestamp: "2026-04-14T21:00Z",
    notes: "55 posts/comments (47% of all activity)",
  },
  {
    from: "A7",
    to: "C2",
    kind: "comments_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "22 posts/comments",
  },
  {
    from: "A7",
    to: "C5",
    kind: "posts_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "OC creation community",
  },
  {
    from: "A8",
    to: "C1",
    kind: "comments_in",
    deltaMinutes: null,
    timestamp: "2026-04-15T05:45Z",
    notes: "11 posts/comments",
  },
  {
    from: "A8",
    to: "C2",
    kind: "comments_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "5 posts/comments",
  },
  {
    from: "A8",
    to: "C6",
    kind: "comments_in",
    deltaMinutes: null,
    timestamp: "2026-04",
    notes: "22 posts (primary community)",
  },

  // Direct cross-account interactions (comments on each other's posts)
  {
    from: "A4",
    to: "A2",
    kind: "comments_on_post",
    deltaMinutes: null,
    timestamp: "2026-04-07",
    notes: "Misato's dad post",
  },
  {
    from: "A4",
    to: "A2",
    kind: "comments_on_post",
    deltaMinutes: null,
    timestamp: "2026-04-06",
    notes: "mucha paja post (removed)",
  },
  {
    from: "A7",
    to: "A2",
    kind: "comments_on_post",
    deltaMinutes: null,
    timestamp: "2026-04-08",
    notes: "Misato's dad post",
  },
  {
    from: "A6",
    to: "A4",
    kind: "comments_on_post",
    deltaMinutes: null,
    timestamp: "2026-04-14",
    notes: "screenshot 5",
  },
  {
    from: "A7",
    to: "A4",
    kind: "comments_on_post",
    deltaMinutes: null,
    timestamp: "2026-04-14",
    notes: "screenshot 5",
  },
  {
    from: "A8",
    to: "A4",
    kind: "comments_on_post",
    deltaMinutes: null,
    timestamp: "2026-04-15",
    notes: "screenshot 5",
  },

  // Temporal proximity (within 3 minutes, different subs)
  {
    from: "A7",
    to: "A8",
    kind: "temporal_proximity",
    deltaMinutes: 0,
    timestamp: "2026-03-22T03:53Z",
    notes: "evangelion / evangelion",
  },
  {
    from: "A8",
    to: "A7",
    kind: "temporal_proximity",
    deltaMinutes: 1,
    timestamp: "2026-03-22T03:51Z",
    notes: "evangelionmemes / evangelion",
  },
  {
    from: "A6",
    to: "A7",
    kind: "temporal_proximity",
    deltaMinutes: 0,
    timestamp: "2026-03-31T16:30Z",
    notes: "Gundam / NeonGenesisEvangelion",
  },
  {
    from: "A2",
    to: "A5",
    kind: "temporal_proximity",
    deltaMinutes: 0,
    timestamp: "2026-04-07T00:07Z",
    notes: "Darkraiposting / MyAnimeList",
  },
  {
    from: "A1",
    to: "A6",
    kind: "temporal_proximity",
    deltaMinutes: 0,
    timestamp: "2026-04-13T21:07Z",
    notes: "manga / DBHeroShooter",
  },
  {
    from: "A1",
    to: "A6",
    kind: "temporal_proximity",
    deltaMinutes: 0,
    timestamp: "2026-04-13T21:53Z",
    notes: "AskReddit / SonicTheHedgehog",
  },
  {
    from: "A1",
    to: "A7",
    kind: "temporal_proximity",
    deltaMinutes: 0,
    timestamp: "2026-04-14T08:27Z",
    notes: "AskReddit / DDLCcirclejerk",
  },
  {
    from: "A1",
    to: "A7",
    kind: "temporal_proximity",
    deltaMinutes: 1,
    timestamp: "2026-04-13T21:31Z",
    notes: "Kingdom / OriginalCharacter",
  },
  {
    from: "A1",
    to: "A6",
    kind: "temporal_proximity",
    deltaMinutes: 1,
    timestamp: "2026-04-13T21:52Z",
    notes: "GOONED / SonicTheHedgehog",
  },
  {
    from: "A6",
    to: "A7",
    kind: "temporal_proximity",
    deltaMinutes: 1,
    timestamp: "2026-04-14T13:41Z",
    notes: "deathbattle / OriginalCharacterDB",
  },
  {
    from: "A5",
    to: "A7",
    kind: "temporal_proximity",
    deltaMinutes: 2,
    timestamp: "2026-03-22T04:31Z",
    notes: "evangelionmemes / evangelionmemes",
  },
  {
    from: "A7",
    to: "A5",
    kind: "temporal_proximity",
    deltaMinutes: 2,
    timestamp: "2026-03-29T15:35Z",
    notes: "NeonGenesisEvangelion / StardustCrusaders",
  },
  {
    from: "A2",
    to: "A8",
    kind: "temporal_proximity",
    deltaMinutes: 3,
    timestamp: "2026-03-26T00:11Z",
    notes: "asushin / NeonGenesisEvangelion",
  },
];

export const wordword4numbers: InvestigationGraph = {
  id: "wordword4numbers",
  title: "wordword4numbers",
  source: "funny3/investigations/wordword4numbers/GRAPH.md",
  nodes: [...accounts, ...communities],
  edges,
};
